from obsidian : 2023-03-15 15:07:43
Affected files:
.obsidian/workspace.json
error-note/error - TypeError - require(...).button is not a function.md
error-note/pragma and pragmaFrag cannot be set when runtime is automatic..md