from obsidian : 2023-03-14 23:32:24
Affected files:
.obsidian/workspace.json
error-note/You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously..md
error-note/error - TypeError - require(...).button is not a function.md